repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-added-large-files
      - id: detect-private-key
      - id: check-merge-conflict
  - repo: local
    hooks:
    - id: format
      name: format
      entry: hatch run default:black
      types: [python]
      language: system
