name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.13"]
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential python3-dev xserver-xorg libpangocairo-1.0-0 libxkbcommon-dev libxcb-cursor0 xvfb libwayland-dev wayland-protocols xwayland qt6-base-dev libwlroots-dev
      - name: Set up uv and Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.13"
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          activate-environment: true
      - name: Setup project environment
        run: |
          uv sync
          uv pip install --no-cache --config-setting backend=wayland --reinstall-package qtile --group dev
      - name: Check formatting
        run: |
          ruff format --check .
      - name: Run tests and generate coverage report
        run: |
          pytest --cov-report=term-missing --cov-report=xml --cov-config=pyproject.toml --cov=src/qtile_bonsai --cov=tests
      - name: Upload coverage reports to codecov
        uses: codecov/codecov-action@v5
        with:
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
