name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: |
          3.10
          3.11
    - name: Set up pip cache
      if: runner.os == 'Linux'
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libpangocairo-1.0-0 libxkbcommon-dev xvfb libwayland-dev wayland-protocols xwayland qt6-base-dev
        pip install hatch
        hatch env create ci
    - name: Check formatting
      run: |
        hatch run ci:format_check .
    - name: Run tests
      run: |
        hatch run ci:pytest
    - name: Generate coverage report
      run: |
        hatch run ci:cov
    - name: Upload coverage reports to codecov
      uses: codecov/codecov-action@v3
